// Shared compound data used across peptide index, individual pages, and glossary
export const COMPOUNDS = [
  {
    slug: "bpc-157",
    name: "BPC-157",
    full: "Body Protection Compound 157",
    category: "Peptide",
    tags: ["Recovery", "Gut Health", "Anti-inflammatory"],
    color: "#FF3D00",
    headline: "The 'wolverine peptide' for accelerated tissue repair.",
    description: "BPC-157 is a synthetic peptide derived from a stomach protein. It accelerates healing of tendons, ligaments, muscles, and gut lining. Extensively studied in animal models with robust anecdotal human evidence.",
    dose: "200–500mcg/day",
    cycle: "4–6 weeks on, 2 weeks off",
    route: "SubQ injection or oral",
    sideEffects: "Generally well-tolerated. Mild injection site discomfort.",
    research: "Extensive animal studies. Widely used in sports medicine globally.",
    popular: true,
  },
  {
    slug: "tb-500",
    name: "TB-500",
    full: "Thymosin Beta-4",
    category: "Peptide",
    tags: ["Recovery", "Flexibility", "Systemic Healing"],
    color: "#FF6A00",
    headline: "Systemic tissue repair and mobility restoration.",
    description: "TB-500 promotes whole-body healing by upregulating actin, the protein that builds cell structure. Reduces inflammation, scar tissue, and improves range of motion. Synergistic with BPC-157.",
    dose: "2–2.5mg, 2x/week (loading), 1x/week (maintenance)",
    cycle: "4–6 weeks loading, then maintenance",
    route: "SubQ injection",
    sideEffects: "Mild fatigue during loading. Brief head rush post-injection.",
    research: "Used in equine medicine for decades. Strong anecdotal human data.",
    popular: true,
  },
  {
    slug: "ghk-cu",
    name: "GHK-Cu",
    full: "Copper Peptide GHK-Cu",
    category: "Peptide",
    tags: ["Anti-aging", "Collagen", "Longevity"],
    color: "#FF9E00",
    headline: "Reverses gene expression associated with aging.",
    description: "GHK-Cu stimulates collagen synthesis, wound healing, and stem cell activation. Has strong anti-inflammatory properties and has been shown to reverse aging-associated gene expression patterns.",
    dose: "1–2mg/day",
    cycle: "4–6 weeks on, 4 weeks off. Topical: indefinite.",
    route: "SubQ injection or topical",
    sideEffects: "Extremely well tolerated. Topical may cause temporary redness.",
    research: "Thousands of published studies in wound healing and anti-aging.",
    popular: true,
  },
  {
    slug: "ipamorelin",
    name: "Ipamorelin",
    full: "Ipamorelin Acetate",
    category: "Peptide",
    tags: ["Growth Hormone", "Sleep", "Recovery"],
    color: "#FFC700",
    headline: "Clean GH release without cortisol or prolactin spike.",
    description: "Ipamorelin is a selective GH secretagogue that triggers natural growth hormone pulses. Unlike other GH peptides, it doesn't elevate cortisol or prolactin. Improves sleep, recovery, and body composition.",
    dose: "200–300mcg before bed",
    cycle: "3–6 months, 5 days on 2 off",
    route: "SubQ injection",
    sideEffects: "Mild water retention. Tingling hands. Slight hunger increase.",
    research: "Solid clinical research. FDA Investigational New Drug status.",
    popular: true,
  },
  {
    slug: "semax",
    name: "Semax",
    full: "Synthetic ACTH/MSH Fragment",
    category: "Nootropic Peptide",
    tags: ["Cognitive", "BDNF", "Neuroprotection"],
    color: "#FF6A00",
    headline: "Prescription cognitive enhancer used in Russia since 1991.",
    description: "Semax is a synthetic peptide based on ACTH that dramatically increases BDNF (Brain-Derived Neurotrophic Factor). Enhances memory, focus, and processing speed. Neuroprotective. Prescription drug in Russia and Ukraine.",
    dose: "200–900mcg/day via nasal spray",
    cycle: "2 weeks on, 1 week off",
    route: "Nasal spray or injection",
    sideEffects: "Mild anxiety at high doses. Tolerance builds with extended use.",
    research: "Approved drug in Russia/Ukraine. Strong clinical evidence base.",
    popular: true,
  },
  {
    slug: "melanotan-i",
    name: "Melanotan I",
    full: "Afamelanotide",
    category: "Peptide",
    tags: ["Tanning", "Skin", "Anti-inflammatory"],
    color: "#FF9E00",
    headline: "FDA-approved melanocortin peptide. Tan without UV damage.",
    description: "Melanotan I (afamelanotide) is a non-selective melanocortin receptor agonist. FDA-approved as Scenesse for erythropoietic protoporphyria. Provides deep tanning without UV exposure. Longer half-life and cleaner profile than MT-II.",
    dose: "0.5–2mg every 3–4 days (loading), 1mg/week (maintenance)",
    cycle: "2–3 weeks loading, then maintenance as needed",
    route: "SubQ injection",
    sideEffects: "Nausea 30–60 min post-injection early on. Monitor moles.",
    research: "FDA-approved (Scenesse) since 2019 for EPP. Extensive trial history.",
    popular: true,
  },
  {
    slug: "melanotan-ii",
    name: "Melanotan II",
    full: "Melanotan II (MT-II)",
    category: "Peptide",
    tags: ["Tanning", "Libido", "Fat Loss"],
    color: "#FF6A00",
    headline: "Multi-target melanocortin agonist for tanning, libido, and appetite.",
    description: "MT-II activates melanocortin 1/3/4/5 receptors producing stronger tanning than MT-I, significant appetite suppression via MC4R, libido enhancement, and some thermogenic fat loss. More potent but shorter acting than Melanotan I.",
    dose: "0.25–1mg/day (loading), 0.5mg 2–3x/week (maintenance)",
    cycle: "8 weeks on, 4 weeks off",
    route: "SubQ injection. Nasal spray ~80% less bioavailable.",
    sideEffects: "Nausea and flushing (diminish after week 1). Spontaneous erections. Monitor moles — avoid with melanoma history.",
    research: "Developed at University of Arizona. Not FDA-approved. Research use only.",
    popular: true,
  },
  {
    slug: "nmn",
    name: "NMN",
    full: "Nicotinamide Mononucleotide",
    category: "Longevity",
    tags: ["NAD+", "Longevity", "Energy"],
    color: "#FF9E00",
    headline: "NAD+ precursor. Core of the Bryan Johnson longevity stack.",
    description: "NMN is a direct precursor to NAD+, the molecule central to energy metabolism and DNA repair. NAD+ declines with age — supplementation supports cellular energy, mitochondrial function, and longevity pathways.",
    dose: "250–1000mg/day AM fasted",
    cycle: "Ongoing — no cycling required",
    route: "Oral. Sublingual for better absorption.",
    sideEffects: "Generally well tolerated. May cause mild GI upset at high doses.",
    research: "Growing human clinical trial evidence. David Sinclair Harvard research.",
    popular: true,
  },
  {
    slug: "retatrutide",
    name: "Retatrutide",
    full: "Retatrutide (RETA)",
    category: "Metabolic Peptide",
    tags: ["Fat Loss", "Metabolic", "GLP-1"],
    color: "#FF3D00",
    headline: "Triple receptor agonist. Most potent fat loss peptide in trials.",
    description: "Retatrutide simultaneously activates GLP-1, GIP, and glucagon receptors — a triple mechanism that produced up to 24% body weight reduction in Phase 2 trials, exceeding semaglutide. Phase 3 trials ongoing.",
    dose: "0.5mg/week titrating to 4–12mg/week",
    cycle: "Minimum 6-month commitment. Slow titration essential.",
    route: "SubQ injection weekly",
    sideEffects: "Nausea, reduced appetite. Muscle loss risk — maintain high protein.",
    research: "Phase 3 trials underway (2025). Phase 2 showed unprecedented results.",
    popular: true,
  },
];

export type Compound = typeof COMPOUNDS[0];

export function getCompound(slug: string): Compound | undefined {
  return COMPOUNDS.find(c => c.slug === slug);
}

export function generateStaticParams() {
  return COMPOUNDS.map(c => ({ slug: c.slug }));
}
